spring.application.name=diverpoool-api

server.port=8080

spring.datasource.url=jdbc:mariadb://localhost:3306/diverpool
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.jackson.time-zone=America/Bogota

